version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Variáveis de ambiente para o Flask
      - FLASK_ENV=production
      - SECRET_KEY=sua_chave_secreta_aqui_substitua_isso
      # Variáveis de ambiente para a conexão com o banco de dados
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db
    volumes:
      - app_uploads:/app/src/static/uploads
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  app_uploads:
  postgres_data:


