version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # Variáveis de ambiente para o EasyPanel
      # O EasyPanel injeta as variáveis de conexão do banco de dados automaticamente
      # Você pode definir outras variáveis aqui, como SECRET_KEY
      SECRET_KEY: ${SECRET_KEY:-sua_chave_secreta_padrao_aqui}
      FLASK_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      # Persistir uploads de arquivos
      - app_uploads:/app/src/static/uploads
    restart: unless-stopped

volumes:
  app_uploads:
    driver: local
